### ISSUE TITLE
Any plans to update to 1.18?

### ISSUE THREAD

**Issue by username-pass** [stormdirus2/Block-Physics-fabricmc#4]
Are there any plans for you to update this to 1.18-1.18.2? I just would like to know whether this is no longer updated or you just forgot about it. It seems like an amazing mod, and I cannot find any alternative to it, but would really like to play it. Thank you.

**Comment by stormdirus2** [comment]
Hello @username-pass !

This is quite late, but yes I am going to support 1.18.2 and beyond.
In fact, as I'm writing this message, Block Physics's sequel is waiting for approval on Modrinth,

It now goes by Disruption and is a Quilt mod. (Fabric mods work on Quilt)

Modrinth: https://modrinth.com/mod/disruption
Github: https://github.com/stormdirus2/disruption
